# Generated by Django 2.2 on 2019-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.BigIntegerField()),
                ('sname', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=25)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
